### ISSUE TITLE
 Unable to scrape tracker in lt 1.1

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1216]
Forwarded from Deluge ticket: http://dev.deluge-torrent.org/ticket/2885

> In the Logs I noticed the following message:
> 
> Unable to scrape tracker: Python argument types in
> 
>     torrent_handle.scrape_tracker(torrent_handle)
> 
> did not match C++ signature:
> 
>     scrape_tracker(libtorrent::torrent_handle {lvalue}, int)
> 
> This prevents the seeds and peers to be scraped properly from the tracker.

I am assuming the user is using libtorrent 1.1.1

**Comment by arvidn** [comment]
is the binding missing the default argument?

**Comment by cas--** [comment]
Yes I assume so

**Comment by arvidn** [comment]
It works for me. I added a test to test.py (in RC_1_1). It should be running on travis and appveyor soon

**Comment by cas--** [comment]
I see it was fixed recently in #1160, thanks :)

**Comment by bderrly** [comment]
I'm still seeing the same error message in my deluged log. I'm running deluge 1.3.13 with libtorrent 1.1.1.0.

**Comment by bderrly** [comment]
...and I discovered that this is due to the fix being only in the RC_1_1 branch, not master.

**Comment by arvidn** [comment]
I merger RC_1_1 into master 2 days ago about
