### ISSUE TITLE
[Stack Overflow] libtorrent::natpmp::update_mapping

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1370]
https://drdump.com/Problem.aspx?ProblemID=249669&login=guest

flylinkdc_x64!libtorrent::natpmp::update_mapping+0x1fb

Repeated 10726 times:
flylinkdc_x64!libtorrent::natpmp::update_mapping+0x200

flylinkdc_x64!libtorrent::natpmp::mapping_expired+0x4f
flylinkdc_x64!boost::asio::detail::wait_handler<std::_Binder<std::_Unforced,void (__cdecl libtorrent::natpmp::*)(boost::system::error_code const & __ptr64,int) __ptr64,std::shared_ptr<libtorrent::natpmp>,std::_Ph<1> const & __ptr64,int & __ptr64> >::do_complete+0xd2
flylinkdc_x64!boost::asio::detail::win_iocp_io_service::do_one+0x25d
flylinkdc_x64!boost::asio::detail::win_iocp_io_service::run+0xba
flylinkdc_x64!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_b36f97b57e062a41dc0986f1cc6f4630> >,std::default_delete<std::tuple<<lambda_b36f97b57e062a41dc0986f1cc6f4630> > > > >::_Run+0x91
flylinkdc_x64!std::_Pad::_Call_func+0x9

![2016-12-01_11-38-05](https://cloud.githubusercontent.com/assets/920705/20787009/acb533e2-b7ba-11e6-878d-cf52d9551717.png)

**Comment by pavel-pimenov** [comment]
![2016-12-01_12-48-44](https://cloud.githubusercontent.com/assets/920705/20789228/938899cc-b7c4-11e6-898e-bd8ba448d0bd.png)

**Comment by aldenml** [comment]
is this something you can reproduce consistently?

**Comment by pavel-pimenov** [comment]
No :-(  only .dmp file
![2016-12-01_22-32-31](https://cloud.githubusercontent.com/assets/920705/20809170/36d12d6e-b816-11e6-8b87-e7e6fd54a740.png)

**Comment by aldenml** [comment]
I see in the diffs that previously there was a `mutex` involved all over the place, but I'm not familiar with this part , can't say anything else.

**Comment by ssiloti** [comment]
It looks like we could get infinite recursion here if `m.act != mapping_t::action::none && m.protocol == portmap_protocol::none` is true for a mapping, which you can see if the case in the second screenshot. That can cause `natpmp::update_mapping` and `natpmp::try_next_mapping` to call each other in a recursive loop. It looks like `natpmp::disable` can put a mapping into that state. What does the bottom of the call stack look like? What's the state of the m_disabled?

**Comment by pavel-pimenov** [comment]
@ssiloti 
![default](https://cloud.githubusercontent.com/assets/920705/25049579/2b4cfb64-214b-11e7-8003-1eef4503e301.png)

**Comment by pavel-pimenov** [comment]
new call stack
https://drdump.com/Problem.aspx?ProblemID=286500&login=guest
help?

![default](https://cloud.githubusercontent.com/assets/920705/25049807/4d582fc0-214c-11e7-994c-4507913e8709.png)

**Comment by ssiloti** [comment]
Just showing the infinite recursion portion of the call stack doesn't help, I need to see the calls that lead up to the recursion.

**Comment by aldenml** [comment]
From time to time I get this error in android, it's UPnP but it looks very similar, an infinite recursion
```
backtrace:
    #00 pc 00314d0c  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZNSt6__ndk110shared_ptrIN10libtorrent4upnpEEC2IS2_EERKNS_8weak_ptrIT_EENS_9enable_ifIXsr14is_convertibleIPS6_PS2_EE5valueENS3_5__natEE4typeE)
    #01 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #02 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #03 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #04 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #05 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #06 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #07 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #08 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #09 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #10 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #11 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #12 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #13 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #14 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #15 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #16 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #17 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #18 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #19 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #20 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #21 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #22 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #23 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #24 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #25 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #26 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #27 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #28 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #29 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #30 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #31 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #32 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #33 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #34 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #35 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #36 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #37 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #38 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #39 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #40 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #41 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #42 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #43 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #44 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #45 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #46 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #47 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #48 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #49 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #50 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #51 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #52 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #53 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #54 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #55 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #56 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #57 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #58 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #59 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #60 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #61 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #62 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
    #63 pc 00310e58  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
```

**Comment by ssiloti** [comment]
In the case of upnp I don't see how that could happen. `act` is always set to `none` before a recursive call is made which should prevent the mapping from being picked again.

**Comment by pavel-pimenov** [comment]
@ssiloti 
natpmp::update_mapping and natpmp::try_next_mapping - top list of crash-dumps
https://drdump.com/AppVersion.aspx?AppVersionID=3636&login=guest

help?

https://drdump.com/Problem.aspx?ProblemID=286500&login=guest

![default](https://cloud.githubusercontent.com/assets/920705/26063134/bd89ddc8-3995-11e7-831b-ceb71c097f08.png)

**Comment by ajax16384** [comment]
according to dump update_mapping called from two places:
````c++
flylinkdc!libtorrent::natpmp::try_next_mapping+0x28 // update_mapping(i + 1);
....
flylinkdc!libtorrent::natpmp::try_next_mapping+0xb4 // update_mapping(int(m - m_mappings.begin()));
````

i persume problem in this line:
````c++
void natpmp::try_next_mapping(int const i)
...
	auto const m = std::find_if(
		m_mappings.begin(), m_mappings.end()
		, [] (mapping_t const& ma) { return ma.act != mapping_t::action::none; });

````
may be it should contain:  
````c++
return ma.act != mapping_t::action::none && ma.protocol != portmap_protocol::none;
````

**Comment by pavel-pimenov** [comment]
watch m_mappings[4] 
![default](https://cloud.githubusercontent.com/assets/920705/26109834/25aeaca8-3a59-11e7-910c-a73ec1bd5d82.png)

**Comment by ajax16384** [comment]
as far as i understand "protocol" was assigned to "portmap_protocol::none", but "act" was not cleared and triggered infinite recusrion. it could be fixed by changing std::find_if or by finding all places that makes "protocol = portmap_protocol::none" and adding "act = mapping_t::action::none"

**Comment by pavel-pimenov** [comment]
@ajax16384 thanks
1. 
![default](https://cloud.githubusercontent.com/assets/920705/26121084/bea3fcac-3a7b-11e7-987b-dc5f6017364f.png)

2.
![default](https://cloud.githubusercontent.com/assets/920705/26121105/cdffbf74-3a7b-11e7-9dfa-541e93db7054.png)

![default](https://cloud.githubusercontent.com/assets/920705/26121124/db151e3e-3a7b-11e7-9fcd-b5e34c23cc51.png)

?

**Comment by ajax16384** [comment]
changes in natpmp::on_reply  will skip this "if (m->act == mapping_t::action::add)" condition but it's ok

**Comment by ssiloti** [comment]
The data doesn't provide any new information. If always setting act to none solves the problem I'd just go with what.

**Comment by ajax16384** [comment]
i guess @pavel-pimenov will collect new crash dump stat with workaround and show if recursion is gone

**Comment by pavel-pimenov** [comment]
i try fix version 1
https://github.com/pavel-pimenov/flylinkdc-r5xx/blob/master/libtorrent/src/natpmp.cpp#L282
date release : 16.05.2017 19:36:56
so far so good:
https://drdump.com/AppVersion.aspx?AppVersionID=3756&login=guest

**Comment by arvidn** [comment]
@pavel-pimenov do you have a patch or PR?

**Comment by ajax16384** [comment]
both "std::find_if" and "set_none" changes  should be applied

**Comment by arvidn** [comment]
is this problem believed to only affect master? i.e. not RC_1_1?

**Comment by arvidn** [comment]
I believe the ``std::find_if`` fix is the only thing necessary. This is a fix for RC_1_1: https://github.com/arvidn/libtorrent/pull/2012

**Comment by ajax16384** [comment]
BTW upnp does not suffer from same error (even it has simialar find_if pattern) cause it "fix" (act!=none && protocol==none):

````c++
void natpmp::update_mapping(int const i)
...
	if (m.act == mapping_t::action::none
		|| m.protocol == portmap_protocol::none)
	{
		try_next_mapping(i);
		return;
	}
````
````c++
void upnp::update_map(rootdevice& d, int const i)
....
	if (m.act == mapping_t::action::none
		|| m.protocol == portmap_protocol::none)
	{
...
		m.act = mapping_t::action::none;  // << fix possible recursion cause
		next(d, i);
		return;
	}
````

**Comment by arvidn** [comment]
I believe this is fixed now

**Comment by gubatron** [comment]
something still broken w/upnp-mappings, getting about 1000 crashes every 24 hours, they look like this:

```
backtrace:
  native: pc 000000000031726c  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZNSt6__ndk110shared_ptrIN10libtorrent4upnpEEC2IS2_EERKNS_8weak_ptrIT_EENS_9enable_ifIXsr14is_convertibleIPS6_PS2_EE5valueENS3_5__natEE4typeE)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
  native: pc 00000000003133b8  /data/app/com.frostwire.android-2/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+124)
```

**Comment by pavel-pimenov** [comment]
@arvidn reopen issue :-( new crash dump:
https://drdump.com/Problem.aspx?ProblemID=303960&login=guest

**Comment by ssiloti** [comment]
I don't see any way the upnp code could get into an infinite recursion which would produce that stack trace. Without a more detailed dump I don't think there's any hope of solving that one.
