### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dbermond** [arvidn/libtorrent#2041]
I'm getting the following error when trying to compile:
```
CXX      chained_buffer.lo
In file included from ../include/libtorrent/sha1_hash.hpp:45:0,
                 from ../include/libtorrent/hasher.hpp:37,
                 from ../include/libtorrent/block_cache.hpp:44,
                 from block_cache.cpp:34:
../include/libtorrent/aux_/typed_span.hpp: In instantiation of ‘libtorrent::aux::typed_span<T, IndexType> libtorrent::aux::typed_span<T, IndexType>::first(libtorrent::aux::typed_span<T, IndexType>::underlying_index) const [with U = int; Cond = void; T = char*; IndexType = int; libtorrent::aux::typed_span<T, IndexType>::underlying_index = int]’:
block_cache.cpp:597:54:   required from here
../include/libtorrent/aux_/typed_span.hpp:75:43: error: could not convert ‘((const libtorrent::aux::typed_span<char*>*)this)->libtorrent::aux::typed_span<char*>::<anonymous>.libtorrent::span<char*>::first(((std::size_t)n))’ from ‘libtorrent::span<char*>’ to ‘libtorrent::aux::typed_span<char*>’
    return this->base::first(std::size_t(n));
                                           ^
make[1]: *** [Makefile:959: block_cache.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/storage/linux/abs/libtorrent-rasterbar-git/src/libtorrent-rasterbar-git/src'
make: *** [Makefile:617: all-recursive] Error 1
```

System Information:
**OS:** Arch Linux x86_64
**libtorrent-rasterbar:** git master (currently at 1.1.3.r1058.g98a034419)
**compiler**: gcc 7.1.1
**boost**/**boost-libs:** 1.64.0

It was compiling perfectly with gcc 6.3.1 and boost/boost-libs 1.63.
This error showed after the packages update.

**Comment by arvidn** [comment]
I don't understand why that line would require a conversion from ``span`` to ``typed_span``. The conversion that happens there is the opposite.

**Comment by arvidn** [comment]
actually, since ``first()`` returns a ``span``, there shouldn't be any conversion at all

**Comment by ssiloti** [comment]
I don't think it matters that the caller is expecting a `span`, the compiler is still going to try to convert the `span` returned by `span::first` to `typed_span` per the return type of `typed_span::first`. I think there needs to be an explicit conversion in `typed_span::first` and similar functions that convert a `span` from the base class to `typed_span`.

**Comment by arvidn** [comment]
oh, I see. I assumed ``typed_span`` just inherited from ``span`` without implementing those functions itself.

**Comment by aldenml** [comment]
I can confirm this issue with the latest android NDK clang too

**Comment by aldenml** [comment]
This should be fixed with https://github.com/arvidn/libtorrent/pull/2047

**Comment by dbermond** [comment]
Thank you all that replied.

Applying #2047 does not fix it for me and gives the following different output:
```
CXX      lazy_bdecode.lo
In file included from ip_notifier.cpp:39:0:
../include/libtorrent/netlink.hpp: In function ‘bool libtorrent::operator==(const libtorrent::basic_nl_endpoint<Protocol>&, const libtorrent::basic_nl_endpoint<Protocol>&)’:
../include/libtorrent/netlink.hpp:114:24: error: no match for ‘operator==’ (operand types are ‘const sockaddr_nl’ and ‘const sockaddr_nl’)
    return l.m_sockaddr == r.m_sockaddr;
           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
../include/libtorrent/netlink.hpp: In function ‘bool libtorrent::operator!=(const libtorrent::basic_nl_endpoint<Protocol>&, const libtorrent::basic_nl_endpoint<Protocol>&)’:
../include/libtorrent/netlink.hpp:120:26: error: no match for ‘operator==’ (operand types are ‘const sockaddr_nl’ and ‘const sockaddr_nl’)
    return !(l.m_sockaddr == r.m_sockaddr);
             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
../include/libtorrent/netlink.hpp: In function ‘bool libtorrent::operator<(const libtorrent::basic_nl_endpoint<Protocol>&, const libtorrent::basic_nl_endpoint<Protocol>&)’:
../include/libtorrent/netlink.hpp:126:24: error: no match for ‘operator<’ (operand types are ‘const sockaddr_nl’ and ‘const sockaddr_nl’)
    return l.m_sockaddr < r.m_sockaddr;
           ~~~~~~~~~~~~~^~~~~~~~~~~~~~
../include/libtorrent/netlink.hpp: In function ‘bool libtorrent::operator>(const libtorrent::basic_nl_endpoint<Protocol>&, const libtorrent::basic_nl_endpoint<Protocol>&)’:
../include/libtorrent/netlink.hpp:132:24: error: no match for ‘operator<’ (operand types are ‘const sockaddr_nl’ and ‘const sockaddr_nl’)
    return r.m_sockaddr < l.m_sockaddr;
           ~~~~~~~~~~~~~^~~~~~~~~~~~~~
make[1]: *** [Makefile:959: ip_notifier.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/storage/linux/abs/libtorrent-rasterbar-git/src/libtorrent-rasterbar-git/src'
make: *** [Makefile:617: all-recursive] Error 1
```

I see that you're discussing a solution on the pull request page. Thank you for the effort.

**Comment by aldenml** [comment]
Ok, hmm... another error, let me focus in get the PR merged first

**Comment by aldenml** [comment]
@dbermond are you compiling in the context of another project, or it's only compiling `libtorrent` the last error. It surprises me and I don't think the code is correct (you shouldn't be able to compare structs directly, in this case `sockaddr_nl`).

@ssiloti did you add those friends operators for a particular reason?

**Comment by ssiloti** [comment]
Those operators are standard boilerplate I copy&pasted from asio. Ideally they would be modified to correctly compare `m_sockaddr`, but if they're not being used I wouldn't object to commenting them out for now.

**Comment by dbermond** [comment]
@aldenml 
I'm compiling libtorrent standalone. Not in the context of another project.
Now I'm not getting anymore this second error that I posted here (related to `sockaddr`). Maybe because of new commits in git master and merging of #2047? Getting only the original error.

I'm attaching a full build log, including the command line options passed to `configure`. Maybe this can help. Should have done this in the initial report though. (note: I'm using `-std=c++11` in `CXXFLAGS` but this does not interfere in the error. In other words, the error is the same without using `-std=c++11`).

Since new commits were made to git master, the error now is a bit different. But seems very close to my initial report.

[libtorrent-gcc7-compile-error.txt](https://github.com/arvidn/libtorrent/files/1046540/libtorrent-gcc7-compile-error.txt)

**Comment by dbermond** [comment]
I can confirm that downgrading gcc to version 6.3.1 "fixes" this problem.

It builds fine with gcc 6.3.1.

So it really seems to be related to gcc 7.1.1.

**Comment by arvidn** [comment]
here's another patch to extend @aldenml 's first patch to cover the remaining functions.
https://github.com/arvidn/libtorrent/pull/2051

**Comment by dbermond** [comment]
Applying #2053 on top of current git master makes it build fine with gcc 7.1.1.

Thank you @aldenml, @arvidn and @ssiloti.
