### ISSUE TITLE
IPv4 address not announced to tracker (BEP 7)

### ISSUE THREAD

**Issue by wangqr** [arvidn/libtorrent#3474]
libtorrent version (or branch):
25a1f1299 on the RC_1_1 branch 

platform/architecture:
archlinux on x86-64

compiler and compiler version:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC)
```

I am using qbittorrent-nox 4.1.3 on a server that has both a public IPv4 and a public IPv6. The tracker also supports both IPv4 and IPv6.

When announcing to the server, there is only the `ipv6=` part in the query, no matter the tracker is connected via IPv4 or IPv6. In case the tracker is connected via IPv6, there is no way for the tracker to know my IPv4 address.

According to [BEP 7](http://www.bittorrent.org/beps/bep_0007.html), IPv4 address should be reported in the `ipv4=` part, if the tracker is connected via IPv6.

2 possible workarounds to this issue:
* add `Connection\InetAddress=<my_ipv4_address>` to qbittorrent's config, so it will be reported in the `ip=` part.
* Add the IPv4 address of the tracker to `/etc/hosts`, so the client always connect to the tracker via IPv4.

Reference: original issue at qbittorrent/qBittorrent#9860

**Comment by arvidn** [comment]
libtorrent will announce twice, once over IPv4 and once over IPv6. Do you not see this behavior?

The `&ipv6=` tracker arguments was disabled deliberately, as it had a few issues. There's no (practical) way for the tracker to verify the source IP, other than the one you're connected from, it may also be an unexpected privacy leak. It was only enabled for private torrents, so I take it that's your scenario.

The `&ipv4=` argument was never implemented by libtorrent. Announcing once from each IP is a much better solution in all respects. Reliability, privacy and scalability (imagine you have two IPv4 interfaces or two IPv6). I understand private trackers still rely on these arguments. I'm inclined to fix this in master, rather than 1.1.x, as the logic around this is a lot cleaner and less error prone.

**Comment by arvidn** [comment]
does this work? https://github.com/arvidn/libtorrent/pull/3477

**Comment by wangqr** [comment]
> libtorrent will announce twice, once over IPv4 and once over IPv6. Do you not see this behavior?

Yes I see this behavior now. Turns out that the (buggy?) tracker is only recording the last announce.
> The `&ipv6=` tracker arguments was disabled deliberately, as it had a few issues. There's no (practical) way for the tracker to verify the source IP, other than the one you're connected from, it may also be an unexpected privacy leak. It was only enabled for private torrents, so I take it that's your scenario.

Yes it is a private torrent.
> does this work? #3477

I'm not able to test this right now because qbittorrent 4.1.3 doesn't compile with libtorrent 1.2.x ([build log](https://gist.github.com/wangqr/2a50251aa0936c77122b000008b0e50b))

**Comment by wangqr** [comment]
@airium Yes the patch works fine. Thanks!

**Comment by arvidn** [comment]
@airium yes, please do. I just released 1.1.11 though, and I'm not sure I will make more releases out of the 1.1.x branch, but it's good to have it there anyway. package-maintainers can still pick it up

**Comment by noblehng** [comment]
I am afraid it still doesn't work for all cases.

The `m_ipv4_interface` is populated at bind time and never update, so if we get a dynamic public ipv4 address, it will report a stalled value. Furthermore, public ipv4 address of devices behind NAT will not be reported in this way either (IIRC, rtorrent will even announce the lan address).

I think, the only sane way to deal with legacy private trackers that doesn't properly support dual stack/multihoming, is to not announce over ipv6 at all except for ipv6 only networks. As a workaround, one could use dnsmasq to blackhole the AAAA record of affected trackers.

**Comment by wangqr** [comment]
Fixed in v1.1.12
