### ISSUE TITLE
re-binding the UDP socket immediately sometimes fails 1.0

### ISSUE THREAD

**Issue by arvidn** [arvidn/libtorrent#454]
@sledgehammer999 I modified your example from https://github.com/arvidn/libtorrent/issues/450 to try to trigger the bug, adding:

```
	session_settings p;
	for (int i = 0; i < 100; ++i)
	{
		p.ssl_listen = 0;
		nativeSession.set_settings(p);
		p.ssl_listen = 4422;
		nativeSession.set_settings(p);
	}
```

on OSX I cannot trigger the issue. I will try on windows as well.

**Comment by sledgehammer999** [comment]
Putting the same for loop makes it happen usually once.
But one time it even failed to also bind the `4422` port using for the TCP/SSL protocol. (after setting it via the settings).

**Comment by arvidn** [comment]
If I increased the loop to 1000 and run it on windows I can get it to fail an assert, which I imagine is related to the bug. This is the assert:
TORRENT_ASSERT(m_v4_outstanding > 0);
in udp_socket::on_read() which is being called with an error code of 995 (ERROR_OPERATION_ABORTED). I'm suspecting that this counter gets set to 0 when the socket is re-used, before the abort callback gets called.

**Comment by arvidn** [comment]
that was a red herring. that was just the counter exceeding the 8 bit limit. nothing that would happen by just re-binding the socket once. I cannot reproduce this on windows 7, built with msvc-12.0

**Comment by arvidn** [comment]
I wonder if this has to do with udp_socket cancelling outstanding operations on close(), but if that fails,  closes the socket. I would imagine closing the socket would make it less likely to have this problem.

**Comment by sledgehammer999** [comment]
If you have a patch, I'll happily test it.

**Comment by arvidn** [comment]
could you give this a try? It's mostly a hunch. https://github.com/arvidn/libtorrent/pull/494

**Comment by sledgehammer999** [comment]
Unfortunately I still get for udp:
> Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by arvidn** [comment]
I believe this is fixed now (please re-open if it isn't)

**Comment by sledgehammer999** [comment]
You haven't merged #494 so technically this is still broken.

**Comment by arvidn** [comment]
ah, right

**Comment by arvidn** [comment]
attempted fix here: https://github.com/arvidn/libtorrent/pull/575

**Comment by sledgehammer999** [comment]
@arvidn I think you can close this now.
