### ISSUE TITLE
python binding with NO_DEPRECATE torrent_info fails

### ISSUE THREAD

**Issue by DiMartinoXBMC** [arvidn/libtorrent#48]
I tried to use python-libtorrent without depricated functions (like this one I built myself [1.0.5 for windows](https://yadi.sk/d/fjwcF9Tvi4Kk6)), but it doesn't work even with [official test here](http://libtorrent.org/python_binding.html). Build [with depricated](https://yadi.sk/d/rZICijFLi4LWu) works fine.
What is the correct way to load torrent file now or should I just stick with depricated build?

Error:

Boost.Python.ArgumentError: Python argument types in
    torrent_info.__init__(torrent_info, dict)
did not match C++ signature:
    __init__(struct _object *, class libtorrent::torrent_info ti, int flags=0)
    __init__(class boost::python::api::object, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, int)
    __init__(class boost::python::api::object, char const *, int, int)
    __init__(struct _object *, class libtorrent::sha1_hash info_hash, int flags=0)

**Comment by arvidn** [comment]
Could you please test this patch? https://github.com/arvidn/libtorrent/pull/50

**Comment by DiMartinoXBMC** [comment]
info = lt.torrent_info(e)
Boost.Python.ArgumentError: Python argument types in
    torrent_info.__init__(torrent_info, dict)
did not match C++ signature:
    __init__(struct _object *, class libtorrent::torrent_info ti, int flags=0)
    __init__(class boost::python::api::object, class libtorrent::entry, int)
    __init__(class boost::python::api::object, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, int)
    __init__(class boost::python::api::object, char const *, int, int)
    __init__(struct _object *, class libtorrent::sha1_hash info_hash, int flags=0)

**Comment by arvidn** [comment]
yeah, the flags argument doesn't have the default value of 0 still. I'll try to fix that too

**Comment by arvidn** [comment]
should be fixed now!

**Comment by DiMartinoXBMC** [comment]
well torrent_info is actually fixed, thanks for that...
test still not working

    while (not h.is_seed()):
AttributeError: 'torrent_handle' object has no attribute 'is_seed'
 

replaced it with while True and it worked.

**Comment by arvidn** [comment]
yeah, that's because is_seed() is actually a deprecated member function. I'll replace it in the example in the docs

**Comment by arvidn** [comment]
this would be equivalent:

-       while (not h.is_seed()):
+       s = h.status()
+       while (not s.is_seeding):
                s = h.status()
