### ISSUE TITLE
Linking failure on macOS 10.15 (Xcode 11.6)

### ISSUE THREAD

**Issue by FranciscoPombal** [arvidn/libtorrent#4965]
**libtorrent version (or branch)**

1.2.8

**platform/architecture**

macOS 10.15 x86_64

**compiler and compiler version**

Xcode 11.6, AppleClang 11.0.3.11030032

**please describe what symptom you see, what you would expect to see instead and
how to reproduce it**

Trying to build qBittorrent on macOS 10.15 (GitHub Actions). The build fails in the linking step with the following message:

```
[357/357] Linking CXX executable qbittorrent.app/Contents/MacOS/qbittorrent
FAILED: qbittorrent.app/Contents/MacOS/qbittorrent 
: && /Applications/Xcode_11.6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -DNDEBUG -isysroot /Applications/Xcode_11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pthread src/app/CMakeFiles/qBittorrent.dir/qBittorrent_autogen/mocs_compilation.cpp.o src/app/CMakeFiles/qBittorrent.dir/application.cpp.o src/app/CMakeFiles/qBittorrent.dir/applicationinstancemanager.cpp.o src/app/CMakeFiles/qBittorrent.dir/cmdoptions.cpp.o src/app/CMakeFiles/qBittorrent.dir/filelogger.cpp.o src/app/CMakeFiles/qBittorrent.dir/main.cpp.o src/app/CMakeFiles/qBittorrent.dir/qtlocalpeer/qtlocalpeer.cpp.o src/app/CMakeFiles/qBittorrent.dir/upgrade.cpp.o src/app/CMakeFiles/qBittorrent.dir/qrc_lang.cpp.o src/app/CMakeFiles/qBittorrent.dir/qrc_webui_translations.cpp.o src/app/CMakeFiles/qBittorrent.dir/qrc_icons.cpp.o src/app/CMakeFiles/qBittorrent.dir/qrc_searchengine.cpp.o src/app/CMakeFiles/qBittorrent.dir/qBittorrent_autogen/TUYZJ7PCOQ/qrc_about.cpp.o src/app/CMakeFiles/qBittorrent.dir/qBittorrent_autogen/TEN4WZ4RQ3/qrc_webui.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Network/Qt5Network_QGenericEnginePlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QCocoaIntegrationPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Widgets/Qt5Widgets_QMacStylePlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5PrintSupport/Qt5PrintSupport_QCocoaPrinterSupportPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QMacHeifPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.o src/app/CMakeFiles/qBittorrent.dir/Users/runner/qbt_tools/vcpkg/installed/x64-osx/share/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.o -o qbittorrent.app/Contents/MacOS/qbittorrent  src/base/libqbt_base.a  src/gui/libqbt_gui.a  src/webui/libqbt_webui.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5MacExtras.a  -lobjc  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Gui.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Widgets.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/platforms/libqcocoa.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqgif.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqicns.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqico.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqjp2.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqjpeg.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqmacheif.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/iconengines/libqsvgicon.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqsvg.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqtga.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqtiff.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqwbmp.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqwebp.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/styles/libqmacstyle.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5AccessibilitySupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5ThemeSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5FontDatabaseSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5GraphicsSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5PrintSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5ClipboardSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Svg.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/printsupport/libcocoaprintersupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Gui.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Widgets.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/platforms/libqcocoa.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqgif.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqicns.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqico.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqjp2.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqjpeg.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqmacheif.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/iconengines/libqsvgicon.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqsvg.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqtga.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqtiff.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqwbmp.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/imageformats/libqwebp.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/styles/libqmacstyle.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5AccessibilitySupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5ThemeSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5FontDatabaseSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5GraphicsSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5PrintSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5ClipboardSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Svg.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/printsupport/libcocoaprintersupport.a  -framework  QuartzCore  -framework  CoreVideo  -framework  IOSurface  /Applications/Xcode_11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libcups.tbd  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5AccessibilitySupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5ThemeSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5FontDatabaseSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5GraphicsSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5ClipboardSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libjasper.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5Svg.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libtiff.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//liblzma.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libjpeg.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libwebpdecoder.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libwebpdemux.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libwebpmux.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libwebp.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5DBus.a  -framework  CoreText  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libfontconfig.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libexpat.a  -framework  ImageIO  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5PrintSupport.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5Widgets.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5Gui.a  -framework  Metal  -framework  CoreGraphics  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libharfbuzz.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libfreetype.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libbrotlienc-static.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libbrotlidec-static.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libbrotlicommon-static.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libz.a  -framework  OpenGL  -framework  AGL  src/base/libqbt_base.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libz.a  -framework  Carbon  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libtorrent-rasterbar.a  -framework CoreFoundation  -framework SystemConfiguration  /Applications/Xcode_11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libiconv.tbd  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libssl.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libcrypto.a  -ldl  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libboost_system.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libboost_date_time.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Network.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/bearer/libqgenericbearer.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Network.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/plugins/bearer/libqgenericbearer.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5Network.a  -framework  SystemConfiguration  -framework  GSS  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libssl.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libcrypto.a  /Applications/Xcode_11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libdl.tbd  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Xml.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libQt5Core.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libQt5Core.a  -framework  DiskArbitration  -framework  IOKit  /Applications/Xcode_11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libm.tbd  -framework  AppKit  -framework  Security  -framework  ApplicationServices  -framework  CoreServices  -framework  CoreFoundation  -framework  Foundation  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libz.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libdouble-conversion.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libicui18n.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libicutu.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libicuuc.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libicuio.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libicudata.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libpcre2-16.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib/libzstd.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libbz2.a  /Users/runner/qbt_tools/vcpkg/installed/x64-osx/lib//libpng16.a && :
Undefined symbols for architecture x86_64:
  "libtorrent::entry::entry(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, libtorrent::entry, libtorrent::aux::strview_less, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, libtorrent::entry> > >)", referenced from:
      BitTorrent::Tracker::processRequest(Http::Request const&, Http::Environment const&) in libqbt_base.a(tracker.cpp.o)
      BitTorrent::Tracker::prepareAnnounceResponse(BitTorrent::Tracker::TrackerAnnounceRequest const&) in libqbt_base.a(tracker.cpp.o)
      void std::__1::allocator_traits<std::__1::allocator<libtorrent::entry> >::construct<libtorrent::entry, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, libtorrent::entry, libtorrent::aux::strview_less, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, libtorrent::entry> > >&>(std::__1::allocator<libtorrent::entry>&, libtorrent::entry*, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, libtorrent::entry, libtorrent::aux::strview_less, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, libtorrent::entry> > >&) in libqbt_base.a(tracker.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
##[error]Process completed with exit code 1.
```

~Full logs available at: https://github.com/FranciscoPombal/qBittorrent/runs/964609798?check_suite_focus=true~ EDIT: accidentally deleted the run, not that important now anyway (https://github.com/arvidn/libtorrent/issues/4965#issuecomment-671301899).

At first I thought this could be due to improperly using deprecated functions, since this has been the cause of similar errors in the past, but not in this case. I'm using libtorrent built with deprecated functions disabled, installed via `vcpkg`, and `-DTORRENT_NO_DEPRECATE` is passed to qBittorrent's compile definitions, as expected. Additionally, the C++ standard used in compilation is `-std=gnu++14`.

Here's the commands used to build qBittorrent:

```bash
cmake -B build -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVERBOSE_CONFIGURE=ON -DCMAKE_TOOLCHAIN_FILE=/Users/runner/qbt_tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-osx -DGUI=ON --graphviz=build/target_graph.dot
cmake --build build
```

This problem seems to be exclusive to macOS, and can be reproduced also when using other CMake generators, such as the `Xcode` generator. Not sure if libtorrent itself is the root cause here, but any help is appreciated.

Additionally, here's `BitTorrent::Tracker::prepareAnnounceResponse`, since it uses the problematic symbol `libtorrent::entry::entry`:

```cpp
using namespace BitTorrent;

// ...

void Tracker::prepareAnnounceResponse(const TrackerAnnounceRequest &announceReq)
{
    const TorrentStats &torrentStats = m_torrents[announceReq.infoHash];

    lt::entry::dictionary_type replyDict {
        {ANNOUNCE_RESPONSE_INTERVAL, ANNOUNCE_INTERVAL},
        {ANNOUNCE_RESPONSE_COMPLETE, torrentStats.seeders},
        {ANNOUNCE_RESPONSE_INCOMPLETE, (torrentStats.peers.size() - torrentStats.seeders)},

        // [BEP-24] Tracker Returns External IP (partial support - might not work properly for all IPv6 cases)
        {ANNOUNCE_RESPONSE_EXTERNAL_IP, toBigEndianByteArray(announceReq.socketAddress).toStdString()}
    };

    // peer list
    // [BEP-7] IPv6 Tracker Extension (partial support - only the part that concerns BEP-23)
    // [BEP-23] Tracker Returns Compact Peer Lists
    if (announceReq.compact) {
        lt::entry::string_type peers;
        lt::entry::string_type peers6;

        if (announceReq.event != ANNOUNCE_REQUEST_EVENT_STOPPED) {
            int counter = 0;
            for (const Peer &peer : asConst(torrentStats.peers)) {
                if (counter++ >= announceReq.numwant)
                    break;

                if (peer.endpoint.size() == 6)  // IPv4 + port
                    peers.append(peer.endpoint);
                else if (peer.endpoint.size() == 18)  // IPv6 + port
                    peers6.append(peer.endpoint);
            }
        }

        replyDict[ANNOUNCE_RESPONSE_PEERS] = peers;  // required, even it's empty
        if (!peers6.empty())
            replyDict[ANNOUNCE_RESPONSE_PEERS6] = peers6;
    }
    else {
        lt::entry::list_type peerList;

        if (announceReq.event != ANNOUNCE_REQUEST_EVENT_STOPPED) {
            int counter = 0;
            for (const Peer &peer : torrentStats.peers) {
                if (counter++ >= announceReq.numwant)
                    break;

                lt::entry::dictionary_type peerDict = {
                    {ANNOUNCE_RESPONSE_PEERS_IP, peer.address},
                    {ANNOUNCE_RESPONSE_PEERS_PORT, peer.port}
                };

                if (!announceReq.noPeerId)
                    peerDict[ANNOUNCE_RESPONSE_PEERS_PEER_ID] = peer.peerId.constData();

                peerList.emplace_back(peerDict);
            }
        }

        replyDict[ANNOUNCE_RESPONSE_PEERS] = peerList;
    }

    // bencode
    QByteArray reply;
    lt::bencode(std::back_inserter(reply), replyDict);
    print(reply, Http::CONTENT_TYPE_TXT);
}
```

**Comment by arvidn** [comment]
my first guess would be that it's a C++ version mismatch between qbt and libtorrent

**Comment by arvidn** [comment]
I see, you don't control the vcpkg build, is that right? and you would like to be able to build with C++14 and still link against a binary built with C++11. That's pretty reasonable. I should address this somehow. I fear the most reliable solution is to remove the performance optimization you get with C++14

**Comment by arvidn** [comment]
I think the core of this issue is that the internal container `entry` uses for dictionaries, is exposed in its API. And depending on whether you're building with C++11 or C++14, that type will change (to take advantage of the new feature that lets you search a map with a `std::string` key, using a `string_view`).

**Comment by FranciscoPombal** [comment]
@arvidn 

> my first guess would be that it's a C++ version mismatch between qbt and libtorrent

> I see, you don't control the vcpkg build, is that right? and you would like to be able to build with C++14 and still link against a binary built with C++11. That's pretty reasonable. I should address this somehow. I fear the most reliable solution is to remove the performance optimization you get with C++14

The vcpkg build uses the exact same environment, so I think it uses C++14 as well actually - the vcpkg port file for libtorrent does not override the `-std` flag, and the default `-std` used in this version of AppleClang is `gnu++14`. The only reason why the standard would be different would be if the toolchain file is somehow overriding that, but  I don't think that's the case.

Either way, I'll try to confirm what standard the vcpkg build is using.

**Comment by FranciscoPombal** [comment]
@arvidn 

Ok, I found the problem. Here is a run where I just installed libtorrent and `cat`ed out the build logs:

https://github.com/FranciscoPombal/qBittorrent/runs/966332551?check_suite_focus=true

Looks like the CMake scripts are incorrectly detecting the compiler default as `C++98`, and subsequently forcing `C++11` mode (which is the minimum for an `RC_1_2` build):

```
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Applications/Xcode_11.6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode_11.6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode_11.6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode_11.6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Compiler default is C++98
-- Building in C++11 mode
...
```

Then, in the actual build step, it is possible to see `-std=gnu++11` passed to the compiler command-line.

This is definitely a bug in the CMake scripts, I'll try to see what's up. ping @zeule

**Comment by zeule** [comment]
There is no compiler default detection in our CMake code (https://github.com/arvidn/libtorrent/blob/RC_1_2/cmake/Modules/LibtorrentMacros.cmake#L67).

**Comment by zeule** [comment]
Seems like `CMAKE_CXX_STANDARD_DEFAULT` is not a public API now? In any case, if it's value is wrong (98 for modern Clang), it is definitely a CMake bug.

**Comment by FranciscoPombal** [comment]
@zeule

I see. I looked at https://github.com/arvidn/libtorrent/blob/3ced76ecf12d9bfe4ce53b77e53a1f7484331560/cmake/Modules/LibtorrentMacros.cmake#L66 and I believe it could be improved:

Instead of fiddling with the `CMAKE_CXX_STANDARD_DEFAULT` (this one appears indeed to not be public anymore)/`CMAKE_CXX_STANDARD`/`CXX_STANDARD`, it is best to use `target_compile_features` with the required features from this list: https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html.

Experience with qBittorrent shows that only requiring `cxx_std_14`/`cxx_std_11`/etc is not enough to enforce a "true minimum standard", because, for example, some compilers (including some versions of GCC) will pass the `cxx_std_14` test while having incomplete C++14 support. To fix this, one must look at the language support status https://gcc.gnu.org/projects/cxx-status.html, compare with the CMake page, and add the strings corresponding to the appropriate proposal numbers.

For example, to ensure the compiler has proper C++14 support in qBittorrent, at the time of writing (this is an interface target that others link to):

```cmake
    # Full C++ 14 support is required
    target_compile_features(qbt_common_cfg
        INTERFACE
            cxx_std_14
            cxx_contextual_conversions
            cxx_binary_literals
            cxx_decltype_auto
            cxx_lambda_init_captures
            cxx_generic_lambdas
            cxx_variable_templates
            cxx_relaxed_constexpr
            cxx_attribute_deprecated
            cxx_digit_separators
    )
```

(you can of course be more terse and "cheat" a little bit by only specifying a feature that was added after all the other ones, such as `cxx_relaxed_constexpr` in the case of GCC, but I think it is better to be explicit here)

The benefit of using target_compile_features this way is that all the important logic gets taken care of automagically.
- If the compiler is capable of supporting the minimum required standard, but defaults to an insufficient standard, CMake will append the appropriate `-std` flag to override the default.
- If the compiler defaults to a sufficiently recent standard, the compiler default is used.
- Even if the compiler default is sufficient, the user can easily override the compiler default (e.g., to select something more recent) by passing `-DCMAKE_CXX_STANDARD=FOO`; this is why this variable should be left alone in the script - so that it can have the correct behavior as a cache variable.

**Comment by FranciscoPombal** [comment]
@arvidn 

The improvement to the CMake script mentioned in the comment above is valuable in and of itself, and would solve this issue by side-effect, but of course the real solution to the problem here would be addressing the issue you mentioned in https://github.com/arvidn/libtorrent/issues/4965#issuecomment-671256900

**Comment by zeule** [comment]
The problem is, somebody has to keep the list of features up to date, possibly also increasing the minimal required CMake version. @arvidn does nor care much about CMake and I'm pretty sure would not do this job. The standard version is, from the other hand, a common and well known value, does not require efforts to update.

**Comment by arvidn** [comment]
Another problem is that not every C++ feature has a feature flag like that. For example, in C++17, `std::string` is noexcept move constructible. Previously, it was in practice, but not guaranteed. Once libtorrent relies on this, what's the `cxx_*` feature name?

If I recall correctly, the main reason to do this dance with C++ versions in the cmake file to begin with was just to fail early, and with a nice error message, when trying to build with an old compiler or without the compiler flag to set the C++ version new enough.

We could just remove all this logic and let the compiler fail instead. It won't be as nice for users, since they may have to read the documentation (! :) ) to find out which version of C++ is required.

**Comment by arvidn** [comment]
or perhaps more relevant. The `is_transparent` feature of comparators in C++14 (which is the feature causing the link error in this ticket). https://en.cppreference.com/w/cpp/container/map/find

**Comment by FranciscoPombal** [comment]
@arvidn @zeule 

Specifying the standard with `CMAKE_CXX_STANDARD` is also not fool-proof. For example, GCC 4.8.5 accepts `14`, but will fail compilation if the code makes use of the `cxx_relaxed_constexpr` feature.

Yes, this method is not perfect - there might not exist a corresponding named feature in https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html for all the features used.

But, in practice, assuming you only want to support completed standards (the case for C++ 11-17 right now), if you list every feature that CMake lets you list for that standard, it's very unlikely that a compiler version includes every one of them except that very specific one. So you only need to write the list once:

```cmake
# Full C++ 11 support is required
target_compile_features(torrent-rasterbar
	INTERFACE
		cxx_std_11
		cxx_rvalue_references
		cxx_reference_qualified_functions
		cxx_nonstatic_member_init
		cxx_variadic_templates
		cxx_generalized_initializers
		cxx_static_assert
		cxx_auto_type
		cxx_trailing_return_types
		cxx_lambdas
		cxx_decltype
		cxx_decltype_incomplete_return_types
		cxx_right_angle_brackets
		cxx_default_function_template_args
		cxx_alias_templates
		cxx_extern_templates
		cxx_nullptr
		cxx_strong_enums
		cxx_enum_forward_declarations
		cxx_attributes
		cxx_constexpr
		cxx_alignas
		cxx_alignof
		cxx_delegating_constructors
		cxx_inheriting_constructors
		cxx_explicit_conversions
		cxx_raw_string_literals
		cxx_user_literals
		cxx_defaulted_functions
		cxx_deleted_functions
		cxx_extended_friend_declarations
		cxx_sizeof_member
		cxx_inline_namespaces
		cxx_unrestricted_unions
		cxx_local_type_template_args
		cxx_range_for
		cxx_final
		cxx_override
		cxx_noexcept
		cxx_defaulted_move_initializers
		cxx_thread_local
)
```

The user should of course read the documentation, but this method is a better initial line of defense than the existing one IMO - both may fail in edge cases, but this one has the advantages listed in https://github.com/arvidn/libtorrent/issues/4965#issuecomment-671322398. Once you upgrade to C++14, you just need to replace this list with the one in https://github.com/arvidn/libtorrent/issues/4965#issuecomment-671322398, and so on...

**Comment by FranciscoPombal** [comment]
https://github.com/arvidn/libtorrent/pull/4968

**Comment by arvidn** [comment]
I agree that even if this list is incomplete, it's probably better than nothing (and better than failing, as it seems to be doing right now)

**Comment by FranciscoPombal** [comment]
I consider this addressed by https://github.com/arvidn/libtorrent/pull/4968.

**Comment by an0n666** [comment]
Is this related to the mac os CI builds failing in qbt? That issue still persists.

**Comment by FranciscoPombal** [comment]
@an0n666 

> Is this related to the mac os CI builds failing in qbt? That issue still persists.

Just looked it up - I believe it is the same problem, yes. Looks like the Travis CI script gets libtorrent from homebrew, and it gets built in C++11 mode, while qBittorrent is built in C++14 mode.

**Comment by FranciscoPombal** [comment]
@an0n666 

I'm working on a CI solution built on GitHub Actions, and this is the only blocker right now. Here is a sample run. It took 1h+ in total due the uncached failed macOS builds. Normally it will be much shorter, as you can see from the time it took for the cached Windows build and the Ubuntu builds to finish:

https://github.com/FranciscoPombal/qBittorrent/runs/984706789

I could get this working already by manually applying https://github.com/arvidn/libtorrent/pull/4968 in CI, but libtorrent 1.2.9 seems to be on the verge of being tagged, and when it does I'm going to update vcpkg with it, so why bother. When this is done, which I hope it will be in the next few days, I will submit a PR with this so we don't have to use Travis + Appveyor + builds.shiki.hu for CI. Hopefully it will be more reliable.

**Comment by arvidn** [comment]
would this help? or something like it? https://github.com/arvidn/libtorrent/pull/5010

**Comment by FranciscoPombal** [comment]
@arvidn unfortunately that doesn't work without breaking current client code in general, see https://github.com/arvidn/libtorrent/pull/5010#discussion_r472537544.

**Comment by arvidn** [comment]
see updated patch!

**Comment by FranciscoPombal** [comment]
@arvidn 

The patch is in good shape now, so clients that build with C++ > 11 and link against libtorrent built with C++11 should be OK as long as they define `TORRENT_CXX11_ABI` (I tested this with qBittorrent and it worked fine).

@Chocobo1 @an0n666 

Once https://github.com/arvidn/libtorrent/pull/5010 lands, macOS travis builds _could_ be fixed by updating the libtorrent bottle and defining `TORRENT_CXX11_ABI` when building qBittorrent. Unfortunately, looks like we are using a specific libtorrent 1.2.6 build from builds.shiki.hu, so this doesn't matter. If we were going to use a newer build, we might as well just build it with C++14 anyway.
