### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by trippleflux** [arvidn/libtorrent#5161]
libtorrent version (or branch):
1.2.10.0-386596aa8

platform/architecture:
Windows x64, Boost 1.74, QT 5.15.1, qBittorrent latest master branch.

compiler and compiler version:
MSVC 2019 16.7.3

This filled up my asserts.log every seconds!

````
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.10.0-386596aa8

#: 1
file: 'include\libtorrent/aux_/allocating_handler.hpp'
line: 125
function: asio_handler_allocate
expression: size <= Size
size: 96

stack:
 0: 00007FF8B0DF565B libtorrent::print_backtrace +295 

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.10.0-386596aa8

#: 2
file: 'include\libtorrent/aux_/allocating_handler.hpp'
line: 140
function: asio_handler_deallocate
expression: size <= Size
size: 96

stack:
 0: 00007FF8B0DF565B libtorrent::print_backtrace +295 
 1: 00007FF8B0DF5B75 libtorrent::assert_fail +109 
 2: 00007FF8B0EED06D libtorrent::session_params::session_params +2329
 3: 00007FF8B0EECF1D libtorrent::session_params::session_params +1993
 4: 00007FF8B0E08CA6 libtorrent::create_torrent::create_torrent +4390
 5: 00007FF8B0E08918 libtorrent::create_torrent::create_torrent +3480
 6: 00007FF8B0EED148 libtorrent::session_params::session_params +2548
 7: 00007FF8FF6A14C2 configthreadlocale +146 
 8: 00007FF9011F6FD4 BaseThreadInitThunk +20  
 9: 00007FF9019DCEC1 RtlUserThreadStart +33  

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.10.0-386596aa8

#: 499
file: 'include\libtorrent/aux_/allocating_handler.hpp'
line: 125
function: asio_handler_allocate
expression: size <= Size
size: 104

stack:
 0: 00007FF8B1E3565B libtorrent::print_backtrace +295 
 1: 00007FF8B1E35B75 libtorrent::assert_fail +109 
 2: 00007FF8B1FB8094 libtorrent::aux::storage_piece_set::remove_piece +197032
 3: 00007FF8B1FA0AB5 libtorrent::aux::storage_piece_set::remove_piece +101321
 4: 00007FF8B1ECF0CE libtorrent::session::operator= +72438
 5: 00007FF8B1ECDECB libtorrent::session::operator= +67827
 6: 00007FF8B1ED480D libtorrent::session::operator= +94773
 7: 00007FF8B1ED5D63 libtorrent::session::operator= +100235
 8: 00007FF8B1EDEDA5 libtorrent::session::operator= +137165
 9: 00007FF8B2009F54 libtorrent::upnp_category +49880
10: 00007FF8B1E48CA6 libtorrent::create_torrent::create_torrent +4390
11: 00007FF8B1E48918 libtorrent::create_torrent::create_torrent +3480
12: 00007FF8B1F2D148 libtorrent::session_params::session_params +2548
13: 00007FF8FF6A14C2 configthreadlocale +146 
14: 00007FF9011F6FD4 BaseThreadInitThunk +20  
15: 00007FF9019DCEC1 RtlUserThreadStart +33  

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:
````

**Comment by arvidn** [comment]
thanks for the report. I believe I've fixed this in the `RC_1_2` branch, but I'll take another look. Fundamentally, it's about increasing the `TORRENT_READ_HANDLER_MAX_SIZE` and `TORRENT_WRITE_HANDLER_MAX_SIZE` in `include/config.hpp`

**Comment by arvidn** [comment]
are you building with `BOOST_ASIO_ENABLE_HANDLER_TRACKING` by any chance?

could you try this patch? https://github.com/arvidn/libtorrent/pull/5170

**Comment by trippleflux** [comment]
@arvidn 

Thanks, was tried aux::handler_storage<104> but still getting assertion but less frequently than before, so changed it into aux::handler_storage<124>, recompiled libtorrent and replace the torrent.dll inside qBittorrent installation folder. Now there is only one assertion :
````
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.10.0-386596aa8

#: 1
file: 'C:\QBITTORRENT\install_msvc64\base\include\libtorrent/aux_/allocating_handler.hpp'
line: 125
function: asio_handler_allocate
expression: size <= Size
size: 96

stack:
 0: 00007FF9DC66565B libtorrent::print_backtrace +295 

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.10.0-386596aa8

#: 2
file: 'C:\QBITTORRENT\install_msvc64\base\include\libtorrent/aux_/allocating_handler.hpp'
line: 140
function: asio_handler_deallocate
expression: size <= Size
size: 96

stack:
 0: 00007FF9DC66565B libtorrent::print_backtrace +295 
 1: 00007FF9DC665B75 libtorrent::assert_fail +109 
 2: 00007FF9DC75D06D libtorrent::session_params::session_params +2329
 3: 00007FF9DC75CF1D libtorrent::session_params::session_params +1993
 4: 00007FF9DC678CA6 libtorrent::create_torrent::create_torrent +4390
 5: 00007FF9DC678918 libtorrent::create_torrent::create_torrent +3480
 6: 00007FF9DC75D148 libtorrent::session_params::session_params +2548
 7: 00007FFA2C8F14C2 configthreadlocale +146 
 8: 00007FFA2E906FD4 BaseThreadInitThunk +20  
 9: 00007FFA2EF3CEC1 RtlUserThreadStart +33  
````

I saw the PR has changed, should i recompile it again?

**Comment by arvidn** [comment]
Yes, please test the updated PR.

**Comment by trippleflux** [comment]
@arvidn 

Confirmed, that PR is fixed it :-), thanks a lot.

**Comment by arvidn** [comment]
thanks for testing!
