### ISSUE TITLE
Python bindings fail to build: $CXXFLAGS used incorrectly

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#5797]
**Please provide the following information**

libtorrent version (or branch): 2.0.1

platform/architecture: FreeBSD 12,2

compiler and compiler version: clang-10

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

```
b2 release optimization=space stage_module --hash address-model=64 -j8
CXXFLAGS = -O2 -pipe -fno-omit-frame-pointer -DTORRENT_DISABLE_LOGGING -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -DLIBICONV_PLUG -isystem /usr/local/include 
LDFLAGS =  /usr/local/lib/libboost_python37.so /usr/local/lib/libiconv.so -fstack-protector-strong 
OS = FREEBSD
/usr/local/share/boost-build/src/build/project.jam:259: in find-jamfile from module project
error: Unable to load Jamfile.
error: Could not find a Jamfile in directory '../../deps/try_signal'.
error: Attempted to find it with pattern '[Bb]uild.jam [Jj]amfile.v2 [Jj]amfile [Jj]amfile. [Jj]amfile.jam'.
error: Please consult the documentation at 'http://www.boost.org'.
/usr/local/share/boost-build/src/build/project.jam:322: in load-jamfile from module project
/usr/local/share/boost-build/src/build/project.jam:64: in load from module project
/usr/local/share/boost-build/src/build/project.jam:89: in load-used-projects from module project
/usr/local/share/boost-build/src/build/project.jam:75: in load from module project
/usr/local/share/boost-build/src/build/project.jam:109: in load-parent from module project
/usr/local/share/boost-build/src/build/project.jam:513: in initialize from module project
/usr/local/share/boost-build/src/build/project.jam:348: in load-jamfile from module project
/usr/local/share/boost-build/src/build/project.jam:64: in load from module project
/usr/local/share/boost-build/src/build/project.jam:142: in project.find from module project
/usr/local/share/boost-build/src/build-system.jam:618: in load from module build-system
/usr/local/share/boost-build/src/kernel/modules.jam:295: in import from module modules
/usr/local/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/usr/local/share/boost-build/src/kernel/boost-build.jam:5: in module scope from module
```

Not one other port out of 30,000 uses boost-build, so it is likely untested.

**Comment by arvidn** [comment]
I think this is addressed by this patch: https://github.com/arvidn/libtorrent/pull/5793
I'm trying to address a few other build issues on debian in there as well, before I land it

**Comment by yurivict** [comment]
With submodules checked out and #5793 included the original problem still occurs.

I am trying revision v2.0.1-115-gaf4de3967.

**Comment by arvidn** [comment]
the original problem being:

```
error: Unable to load Jamfile.
error: Could not find a Jamfile in directory '../../deps/try_signal'.
error: Attempted to find it with pattern '[Bb]uild.jam [Jj]amfile.v2 [Jj]amfile [Jj]amfile. [Jj]amfile.jam'.
```

is that right?

Do you have the file `../../deps/try_signal/Jamfile`?

**Comment by yurivict** [comment]
Sorry, submodules were linked to the wrong location.

Now it fails this way:
```
b2 release address-model=64 -j8 libtorrent-python=on python=3.7 python-install-path=build/lib.freebsd-12.2-STABLE-amd64-3.7 install_module --project-config=/tmp/tmpu7t9nafn
CXXFLAGS = -O2 -pipe -fno-omit-frame-pointer -DTORRENT_DISABLE_LOGGING -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -DLIBICONV_PLUG -isystem /usr/local/include
LDFLAGS =  /usr/local/lib/libboost_python37.so /usr/local/lib/libiconv.so -fstack-protector-strong
OS = FREEBSD
...patience...
...patience...
...patience...
...found 4073 targets...
...updating 214 targets...
clang-linux.compile.c++.without-pch bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/module.o
clang++: error: cannot specify -o when generating multiple output files

  "clang++" -c -x c++ -std=c++14 -fPIC -O3 -Wall -Wno-inline  -DLIBICONV_PLUG -DTORRENT_DISABLE_LOGGING -O2 -fno-omit-frame-pointer -fno-strict-aliasing -fstack-protector-strong -fvisibility-inlines-hidden -isystem -pipe /usr/local/include -fvisibility=hidden -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_ASIO_NO_DEPRECATED -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_SYSTEM_NO_DEPRECATED -DNDEBUG -DTORRENT_LINKING_SHARED -DTORRENT_USE_I2P=1 -D_FILE_OFFSET_BITS=64 -D_WIN32_WINNT=0x0600 -I"../../deps/try_signal" -I"../../include" -I"../../include/libtorrent" -I"/opt/local/include" -I"/usr/local/include" -I"/usr/local/include/python3.7m" -I"/usr/local/opt/boost/include" -I"/usr/sfw/include" -I"src"  -o "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/module.o" "src/module.cpp"

...failed clang-linux.compile.c++.without-pch bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/module.o...
clang-linux.compile.c++.without-pch ../../bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/threading-multi/src/alert.o
clang++: error: cannot specify -o when generating multiple output files
```

**Comment by arvidn** [comment]
do you see anything wrong with that command line?

I see a single output:
```
 -o "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/module.o"
```
and a single input:
```
"src/module.cpp"
```

If I would guess, `-pipe` may be involved. Also, the libraries in `LDFLAGS` look a bit suspicious too, you're not supposed to need those (but it isn't the linking step that fails)

**Comment by yurivict** [comment]
This command fails:
```

$ "clang++10" -c -x c++ -std=c++14 -fPIC -O3 -Wall -Wno-inline  -DLIBICONV_PLUG -DTORRENT_DISABLE_LOGGING -O2 -fno-omit-frame-pointer -fno-strict-aliasing -fstack-protector-strong -fvisibility-inlines-hidden -isystem -pipe /usr/local/include -fvisibility=hidden -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_ASIO_NO_DEPRECATED -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_SYSTEM_NO_DEPRECATED -DNDEBUG -DTORRENT_LINKING_SHARED -DTORRENT_USE_I2P=1 -D_FILE_OFFSET_BITS=64 -D_WIN32_WINNT=0x0600 -I"../../deps/try_signal" -I"../../include" -I"../../include/libtorrent" -I"/opt/local/include" -I"/usr/local/include" -I"/usr/local/include/python3.7m" -I"/usr/local/opt/boost/include" -I"/usr/sfw/include" -I"src"  -o "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/error_code.o" src/error_code.cpp
clang++: error: cannot specify -o when generating multiple output files
```

because of this place: ```-isystem -pipe /usr/local/include```.

```/usr/local/include``` is an argument of ``````-isystem```, somebody inserted ```-pipe``` there.

The original ```CXXFLAGS``` passe to build has them in correct order:
```
-O2 -pipe -fno-omit-frame-pointer -DTORRENT_DISABLE_LOGGING -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -DLIBICONV_PLUG -isystem /usr/local/include
```

**Comment by arvidn** [comment]
great find! It seems that the `$CXXFLAGS` (and the `cxxflags` feature specifically) are treated differently when I add them as a property directly on the target, as opposed to passing them in on the command line. I suppose they're really meant to be used from the command line. It would be pretty easy to fix this by making `setup.py` read the `CXXFLAGS` and `$LDFLAGS` environment variables and pass them in. But, I would expect this to be a problem when building the main library as well. Is it not?

Can you point me to the script that invokes the build in the ports tree?

**Comment by yurivict** [comment]
The main library is built from a separate port and it builds okay.

The Python binding port is /usr/ports/net-p2p/py-libtorrent-rasterbar, its Makefile has USES=python, this calls ```setup.py``` under the hood.

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/5852 I will merge this into `RC_2_0` and `master` later

**Comment by arvidn** [comment]
Long term, I will move towards specifying flags like these explicitly, on the command line, rather than via environment variables. To make builds a bit more reliable. But I would need to familiarize myself a bit more with the ports tree first. I appreciate that include paths and library paths aren't available automatically.

In fact, it would be nice if headers weren't installed to `/usr/local/include` but rather, the include paths directly into the port tree for all dependencies were added to the build. so there would be no chance to accidentally pick up a header from a library that isn't a dependency.

**Comment by arvidn** [comment]
I believe this is fixed in `RC_1_2` right now (will be included in the next release, 1.2.13)
