### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by chchia** [arvidn/libtorrent#5936]
**Please provide the following information**

libtorrent version (or branch):
master or RC_2_0

platform/architecture:
docker hub linux amd64

compiler and compiler version:

compiling using docker.com
```
    cd libtorrent-rasterbar && \
    apk add --no-cache make cmake g++ boost-dev openssl-dev && \
    cmake -DCMAKE_INSTALL_LIBDIR=lib . && \
    make -j`nproc` && \
    make install && \
```

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
 
i had been compiling for many months without problem, and since about 10 days ago i am seeing this.
```
Cloning into 'simulation/libsimulator'...
fatal: reference is not a tree: 8e3f7fdcb255c17161f37c2e45de28d819379b12
Unable to checkout '8e3f7fdcb255c17161f37c2e45de28d819379b12' in submodule path 'libtorrent-rasterbar/simulation/libsimulator'
```
it seems referring to a branch that not exist? please help me how do i fix this.
![image](https://user-images.githubusercontent.com/1291771/106425454-ce149d80-649e-11eb-8c36-2ebbd3308fc6.png)

looking in to this commit commit 8e3f7fdcb255c17161f37c2e45de28d819379b12
https://github.com/arvidn/libsimulator/commit/8e3f7fdcb255c17161f37c2e45de28d819379b12

it show 
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

![image](https://user-images.githubusercontent.com/1291771/106426652-f6050080-64a0-11eb-99e2-e82c358f5c81.png)

maybe this is the reason?

**Comment by arvidn** [comment]
I believe this should fix it: https://github.com/arvidn/libtorrent/pull/5938

**Comment by chchia** [comment]
@arvidn 

unfortunately, the same problem still persist.

![image](https://user-images.githubusercontent.com/1291771/106545808-01116c80-6545-11eb-86cf-5a0e4a1b7c30.png)

i had tried both RC_2_0 and master branch, both have same result.

**Comment by chchia** [comment]
For your info, this is the **last working commit**:
https://github.com/arvidn/libsimulator/commit/8c44c29faf6718f4866fc9275779f302ca8672a0

![image](https://user-images.githubusercontent.com/1291771/106547392-19cf5180-6548-11eb-8848-b16036075c8e.png)

**Comment by arvidn** [comment]
the fix was made in `RC_2_0`, and it hasn't been merged into `master` yet.

**Comment by chchia** [comment]
i had tried both RC_2_0 and master branch, both have same result.

**Comment by arvidn** [comment]
the `libsimulator` submodule in `RC_2_0` is 12a83d0, what do you see it as?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/tree/RC_2_0/simulation

**Comment by chchia** [comment]
Submodule path 'simulation/libsimulator': checked out '12a83d04f2ffec2dfdf23b0f3b63a148628d939a'
 yes and no more this error.
![image](https://user-images.githubusercontent.com/1291771/106567434-c8858900-656c-11eb-818a-4457521c8952.png)

i will try to compile now and report back.

**Comment by chchia** [comment]
@arvidn Hi Arvid, thanks i confirm compilation is success.

however, even with this latest build i am still facing tracker Not contacted yet issues.
https://github.com/qbittorrent/qBittorrent/issues/14323

not sure if this is qbittorrent or libtorrent issues. i will try to compile one of it with working commit and see.

thanks.
