### ISSUE TITLE
Inconsistent values in `torrent_status`

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#6284]
libtorrent version (or branch): RC_2_0

platform/architecture: Windows 10 21H1 x64

compiler and compiler version: MSVC2019

When testing BitTorrent v2 (downloading https://libtorrent.org/bittorrent-v2-test.torrent), I ran into the problem when
`torrent_status.total_wanted_done` becomes greater than `torrent_status.total_wanted` (1534288134 vs 1534222888).

**Comment by glassez** [comment]
Another issue with test torrent above:

I can't finish downloading it to the end, it stops at 99.9%. If I recheck it after that, then I get the following assert failure:
```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 2.0.4.0-f9836137a

file: 'libtorrent\src\hash_picker.cpp'
line: 359
function: set_block_hash
expression: merkle_tree.has_node(block_tree_index)

stack:
 0: 00007FFCEC6B2982 libtorrent::print_backtrace +242  libtorrent\src\assert.cpp:189
 1: 000000D96DCFAA90
 2: 0000000000000001
```

**Comment by arvidn** [comment]
two of those issues are addressed here: https://github.com/arvidn/libtorrent/pull/6290

**Comment by glassez** [comment]
Now it crashes somewhere inside https://github.com/arvidn/libtorrent/blob/b93a740d92065aa3c24adb058d05f562604a3c8c/src/torrent.cpp#L3881
Exactly in https://github.com/arvidn/libtorrent/blob/b93a740d92065aa3c24adb058d05f562604a3c8c/include/libtorrent/aux_/alloca.hpp#L72

**Comment by glassez** [comment]
When I add torrent with existing data on disk it fails when checking it:
```
version: 2.0.4.0-f9836137a

file: 'libtorrent\include\libtorrent/span.hpp'
line: 169
function: operator []
expression: idx < m_len

stack:
 0: 00007FF80B002982 libtorrent::print_backtrace +242  libtorrent\src\assert.cpp:189
 1: 000000AD7B9FB240
 2: 0000000000000001
```

**Comment by arvidn** [comment]
sorry about that. one of the changes were incorrect. I need to extend test coverage here clearly

**Comment by arvidn** [comment]
I've landed my patch. Is this still an issue? I forget whether I addressed it or not:

> When testing BitTorrent v2 (downloading https://libtorrent.org/bittorrent-v2-test.torrent), I ran into the problem when
> torrent_status.total_wanted_done becomes greater than torrent_status.total_wanted (1534288134 vs 1534222888).

**Comment by glassez** [comment]
> I've landed my patch. Is this still an issue? I forget whether I addressed it or not:
> 
> > When testing BitTorrent v2 (downloading https://libtorrent.org/bittorrent-v2-test.torrent), I ran into the problem when
> > torrent_status.total_wanted_done becomes greater than torrent_status.total_wanted (1534288134 vs 1534222888).

I'll keep an eye on it. If it shows up again, I'll notify you.

**Comment by arvidn** [comment]
I'm pretty sure these isses have been addressed in `RC_2_0`

**Comment by glassez** [comment]
@arvidn 
Was the fix backported in 1.2.x?
Seems the issue is still here: https://github.com/qbittorrent/qBittorrent/issues/18897.

**Comment by luzpaz** [comment]
bumping for visibilty
